### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by michakraus** [vincentcp/CompactTranslatesDict.jl#1]
I tried to experiment with CompactTranslatesDict.jl, but got several errors regarding missing functions and structures from BasisFunctions.jl, which do not exist (anymore), namely

- dense_evaluation_operator()
- default_gramoperator()
- UniformDiracCombMeasure
- FourierMeasure

I suppose CompactTranslatesDict.jl is not in sync with the current version of BasisFunctions.jl.

**Comment by vincentcp** [comment]
I am sorry for the inconvenience. The package is still in development. The master of `CompactTranslatesDict.jl` uses features that are in the development branch of `BasisFunctions.jl`.

**Comment by michakraus** [comment]
Don't worry. And thanks a lot for the clarification. I wasn't able to get `CompactTranslatesDict.jl` to work with the development branch of `BasisFunctions.jl` either, but I will just wait for the next release.

**Comment by vincentcp** [comment]
De `test` folder contains a `Manifest.toml` file. This file contains the configuration that is used to get the Travis tests working. But again: a lot of tests are missing. 
Last weekend, the `BasisFunctions.jl` and `FrameFun.jl` master was merged with development.

**Comment by michakraus** [comment]
Thanks for the hint. I still was behind that merge. Seems to work now. I can import the package and all tests are passing (also without the Manifest file from the test folder).
